analysis:
  confidence_threshold: 0.75
  cross_validation: true
  report_format: medical_standard
engines:
  audio:
    enabled: true
    language: ko
    model: whisper-base
  image:
    enabled: true
    languages:
    - ko
    - en
    ocr_engine: easyocr
  text:
    enabled: true
    language: ko
    use_transformers: true
  video:
    enabled: true
    sample_frames: 5
project:
  domain: medical
  name: My Analysis Project
  version: 1.0.0
ui:
  layout: four_step
  theme: medical
  title: 의료 컨퍼런스 분석 시스템
